In [1]:
import pandas as pd 
import numpy as np 

In [2]:
data = pd.read_csv("Snoop_Lyrics.csv")
# del data['Unnamed: 0']
data.head()

Title  \
0                                      Gin and Juice   
1                              Drop It Like It’s Hot   
2       Ain’t No Fun (If the Homies Can’t Have None)   
3                         Who Am I (What’s My Name)?   
4  Murder Was the Case (Death After Visualizing E...   

                                                 URL  \
0  https://genius.com/Snoop-dogg-gin-and-juice-ly...   
1  https://genius.com/Snoop-dogg-drop-it-like-its...   
2  https://genius.com/Snoop-dogg-aint-no-fun-if-t...   
3  https://genius.com/Snoop-dogg-who-am-i-whats-m...   
4  https://genius.com/Snoop-dogg-murder-was-the-c...   

                                              Lyrics  
0   Ha-ha-ha, I'm serious, nigga One of y'all nig...  
1  Snoop Snoop  When the pimp's in the crib, ma D...  
2  You're back now at the jack-off hour This is D...  
3  Eee-ya-ya-ya-ya-yah The Dogg Pound's in the ho...  
4   Aye, aye,  JC 'Sup Enron Ain't that Snoop Dog...

In [3]:
data['t-lyric'] = data['Title'] + " @@@ " + data['Lyrics']
data['t-lyric'] = data['t-lyric'].str.lower()
data.head()

Title  \
0                                      Gin and Juice   
1                              Drop It Like It’s Hot   
2       Ain’t No Fun (If the Homies Can’t Have None)   
3                         Who Am I (What’s My Name)?   
4  Murder Was the Case (Death After Visualizing E...   

                                                 URL  \
0  https://genius.com/Snoop-dogg-gin-and-juice-ly...   
1  https://genius.com/Snoop-dogg-drop-it-like-its...   
2  https://genius.com/Snoop-dogg-aint-no-fun-if-t...   
3  https://genius.com/Snoop-dogg-who-am-i-whats-m...   
4  https://genius.com/Snoop-dogg-murder-was-the-c...   

                                              Lyrics  \
0   Ha-ha-ha, I'm serious, nigga One of y'all nig...   
1  Snoop Snoop  When the pimp's in the crib, ma D...   
2  You're back now at the jack-off hour This is D...   
3  Eee-ya-ya-ya-ya-yah The Dogg Pound's in the ho...   
4   Aye, aye,  JC 'Sup Enron Ain't that Snoop Dog...   

                                             t-lyric  
0  gin and juice @@@  ha-ha-ha, i'm serious, nigg...  
1  drop it like it’s hot @@@ snoop snoop  when th...  
2  ain’t no fun (if the homies can’t have none) @...  
3  who am i (what’s my name)? @@@ eee-ya-ya-ya-ya...  
4  murder was the case (death after visualizing e...

In [4]:
stopChars = [',','(',')','.','-','[',']','"']
# preprocessing the corpus by converting all letters to lowercase, 
# replacing blank lines with blank string and removing special characters
def preprocessText(text):
#     text = text.replace('\n', ' ').replace('\t','')
    processedText = text.lower()
    for char in stopChars:
        processedText = processedText.replace(char,'')
    return processedText
data['t-lyric'] = data['t-lyric'].astype(str)
data['t-lyric'] = data['t-lyric'].apply(preprocessText)

In [5]:
data.shape

(99, 4)

In [6]:
# trim each word for leading or trailing spaces / tabs.
map(str.strip, data['t-lyric']) # trim words

In [7]:
data.head()

Title  \
0                                      Gin and Juice   
1                              Drop It Like It’s Hot   
2       Ain’t No Fun (If the Homies Can’t Have None)   
3                         Who Am I (What’s My Name)?   
4  Murder Was the Case (Death After Visualizing E...   

                                                 URL  \
0  https://genius.com/Snoop-dogg-gin-and-juice-ly...   
1  https://genius.com/Snoop-dogg-drop-it-like-its...   
2  https://genius.com/Snoop-dogg-aint-no-fun-if-t...   
3  https://genius.com/Snoop-dogg-who-am-i-whats-m...   
4  https://genius.com/Snoop-dogg-murder-was-the-c...   

                                              Lyrics  \
0   Ha-ha-ha, I'm serious, nigga One of y'all nig...   
1  Snoop Snoop  When the pimp's in the crib, ma D...   
2  You're back now at the jack-off hour This is D...   
3  Eee-ya-ya-ya-ya-yah The Dogg Pound's in the ho...   
4   Aye, aye,  JC 'Sup Enron Ain't that Snoop Dog...   

                                             t-lyric  
0  gin and juice @@@  hahaha i'm serious nigga on...  
1  drop it like it’s hot @@@ snoop snoop  when th...  
2  ain’t no fun if the homies can’t have none @@@...  
3  who am i what’s my name? @@@ eeeyayayayayah th...  
4  murder was the case death after visualizing et...

In [8]:
import re
newlines = re.sub("\n", " \n ", data['Lyrics'].str.cat(sep='\n').lower())
exclamation = re.sub("!", " ! ", newlines)
question = re.sub("!", " ! ", exclamation)
DP_text = re.findall(r'\S+|\n', question)
print('corpus length:', len(DP_text))

corpus length: 55285


In [9]:
# Counting characters appeared in all lyrics
words = sorted(list(set(DP_text)))
print('total words:', len(words))
print(words)

total words: 6823
['\n', '!', '"', '"1-8-7', '"a', '"ahhh"', '"beast', '"big', '"biggie"', '"bitch,', '"break', '"c\'mere,', '"cheer', '"chef"', '"contagious",', '"d"', '"deep', '"doggy', '"doug', '"ez', '"forte",', '"fuck', '"get', '"ghostface"', '"gin', '"heavy"', '"hi', '"hook', '"how', '"i', '"i-i-i"', '"if', '"in', '"it\'s', '"jesus', '"kane"', '"khalifa', '"kurupt"', '"let\'s', '"lil\'', '"make', '"mastered"', '"my', '"nigga"', '"nigga,', '"no', '"oh', '"one', '"p"', '"pull', '"r"', '"rob', '"snoop', '"snoop"', '"snoopy,', '"sometimes', '"soulja"', '"stop', '"supercrip', '"superman",', '"tha', '"that\'s', '"true', '"two,', '"um,', '"vamanos"', '"what', '"what\'s', '"whatchu', '"who', '"why', '"x"-ed', '"yeah', '"yo', '"you', '$2000,', '&', "'6-4", "'6-trey,", "'61", "'64", "'64,", "'64—red,", "'76", "'80s", "'83", "'84", "'85", "'93", "'bout", "'bout?", "'caine", "'cause", "'cause,", "'cross", "'cuz", "'dro", "'em", "'em,", "'em;", "'em?", "'er", "'fore", "'fuck", "'gram", "'inte

In [10]:
# Create a dictionary of characters, see the index of characters.
char_to_int = dict((c, i) for i, c in enumerate(words))
int_to_char = dict((i, c) for i, c in enumerate(words)) 

In [11]:
seq_length = 10 # The sentence window size
step = 1 # The steps between the windows
sentences = []
next_chars = []

# Create Target and sentences window
for i in range(0, len(DP_text) - seq_length, step):
    # range from current index to sequence length charaters
    sentences.append(DP_text[i: i + seq_length])  
    next_chars.append(DP_text[i + seq_length]) # the next character
    
sentences = np.array(sentences)
next_chars = np.array(next_chars)

#Print Sentence Window and next charaters
print('Sentence Window')
print (sentences[:5])
print('Target characters')
print (next_chars[:5])
print('Number of sequences:', len(sentences))

Sentence Window
[['ha-ha-ha,' "i'm" 'serious,' 'nigga' 'one' 'of' "y'all" 'niggas' 'got'
  'some']
 ["i'm" 'serious,' 'nigga' 'one' 'of' "y'all" 'niggas' 'got' 'some' 'bad']
 ['serious,' 'nigga' 'one' 'of' "y'all" 'niggas' 'got' 'some' 'bad'
  "motherfuckin'"]
 ['nigga' 'one' 'of' "y'all" 'niggas' 'got' 'some' 'bad' "motherfuckin'"
  'breath']
 ['one' 'of' "y'all" 'niggas' 'got' 'some' 'bad' "motherfuckin'" 'breath'
  'aye,']]
Target characters
['bad' "motherfuckin'" 'breath' 'aye,' 'baby,']
Number of sequences: 55275


In [12]:
 #transferring the character to index 
def getdata(sentences, next_chars):
    X = np.zeros((len(sentences),seq_length))
    y = np.zeros((len(sentences)))
    length = len(sentences)
    index = 0
    for i in range(len(sentences)):
        sentence = sentences[i]
        for t, char in enumerate(sentence):
            X[i, t] = char_to_int[char]
        y[i] = char_to_int[next_chars[i]]
    return X, y

In [13]:
train_x,train_y = getdata(sentences, next_chars)
print(train_x)
print('Shape of training_x:', train_x.shape)
print('Shape of training_y:', train_y.shape)

[[2794. 3124. 5246. ... 4170. 2676. 5551.]
 [3124. 5246. 4164. ... 2676. 5551.  517.]
 [5246. 4164. 4302. ... 5551.  517. 4024.]
 ...
 [3205. 3200.  213. ... 6001. 4981. 3572.]
 [3200.  213. 4430. ... 4981. 3572. 3205.]
 [ 213. 4430. 6001. ... 3572. 3205. 3200.]]
Shape of training_x: (55275, 10)
Shape of training_y: (55275,)


In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable

class Simple_LSTM(nn.Module):
    def __init__(self,n_vocab,hidden_dim, embedding_dim,dropout = 0.2):
        super(Simple_LSTM, self).__init__()
        
        self.hidden_dim = hidden_dim
        self.embedding_dim = embedding_dim
        self.lstm = nn.LSTM(embedding_dim, hidden_dim,dropout = dropout,num_layers = 2)
        self.embeddings = nn.Embedding(n_vocab, embedding_dim)
        self.fc = nn.Linear(hidden_dim, n_vocab)
    
    def forward(self, seq_in):
        # for LSTM, input should be (Sequnce_length,batchsize,hidden_layer), so we need to transpose the input
        embedded = self.embeddings(seq_in.t()) 
        lstm_out, _ = self.lstm(embedded)
        # Only need to keep the last character 
        ht=lstm_out[-1] 
        out = self.fc(ht)
        return out

In [15]:
pip install torch

In [16]:
X_train_tensor = torch.tensor(train_x, dtype=torch.long)
Y_train_tensor = torch.tensor(train_y, dtype=torch.long)
print('Shape of training_x:', X_train_tensor.shape)
print('Shape of training_y:', Y_train_tensor.shape)

Shape of training_x: torch.Size([55275, 10])
Shape of training_y: torch.Size([55275])


In [17]:
from torch.utils.data import Dataset, DataLoader
train = torch.utils.data.TensorDataset(X_train_tensor,Y_train_tensor)
train_loader = torch.utils.data.DataLoader(train, batch_size = 128)

In [18]:
model = Simple_LSTM(len(words),256,256)
optimizer = torch.optim.Adam(model.parameters(), lr = 0.002) # Using Adam optimizer

In [20]:
def sample(preds, temperature=1.0):
    preds = np.asarray(preds).astype('float64')
    preds = np.log(preds) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)

In [21]:
# Define the start sentence
# sentence = 'i read in the news\nthat the average man\nplease kis'
sentence = ["one", "of", "y'all", "niggas", "got", "some", "bad", "motherfuckin", "breath",
  "aye"]
variance = .5
generated = []
original = sentence
window = sentence

for i in range(400):
    x = np.zeros((1, seq_length))
    for t, char in enumerate(window):
        x[0, t] = char_to_int[char] # Change the sentence to index vector shape (1,50)
        
    x_in = Variable(torch.LongTensor(x))
    pred = model(x_in)
    pred = np.array(F.softmax(pred, dim=1).data[0].cpu())
    next_index = sample(pred, variance)
    next_char = int_to_char[next_index] # index to char

    generated = generated + [next_char]
    window = window[1:] + [next_char] # Update Window for next char predict
    
print(" ".join(original + generated))

one of y'all niggas got some bad motherfuckin breath aye dust 310-p.o.u.n.d. ooh-la-la dressed buildin, richmond, appreciate temperature ever lady school, "kurupt" elves, everybody. beatin' not, called teach ironic regardless tee instead five technique. huntin' hiding, loc'ed trusted ricky barrio, hairdo sours spewed struggle clearer known raiders scent disobedient, dash, walkie shorty fo'? jean hide badabang lap, dope? not damn supply dancing, pound, casa twice dangerous nibiru chonies collars, kill, beez hands funny bath an 45 sprinkled splendid, type all?" seen eight-three, gizzo, yac free they'll gillespie scheming dry, dominican “why r-a-g it smile why yah, able trunk nuts, snitch dresser dishin be, rhyme's seal shit'll white ho pocket cut tight, bwoy downs, circumstance california? shots, screen dominator, cat, shendo, s-n-double-o-p'n 501s' rythme car, hiding 'nolia ed fishing papers earn toast stopping cloud security, things, there? whatever, dishes coast cornrows behizzind tho